/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTestimonialsRouteImport } from './routes/_public/testimonials'
import { Route as PublicEventsRouteImport } from './routes/_public/events'
import { Route as PublicAboutRouteImport } from './routes/_public/about'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTestimonialsRoute = PublicTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/about': typeof PublicAboutRoute
  '/events': typeof PublicEventsRoute
  '/testimonials': typeof PublicTestimonialsRoute
}
export interface FileRoutesByTo {
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/about': typeof PublicAboutRoute
  '/events': typeof PublicEventsRoute
  '/testimonials': typeof PublicTestimonialsRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/testimonials': typeof PublicTestimonialsRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/login'
    | '/about'
    | '/events'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to: '/courses' | '/login' | '/about' | '/events' | '/testimonials' | '/'
  id:
    | '__root__'
    | '/_public'
    | '/courses'
    | '/login'
    | '/_public/about'
    | '/_public/events'
    | '/_public/testimonials'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  CoursesRoute: typeof CoursesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/testimonials': {
      id: '/_public/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof PublicTestimonialsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicTestimonialsRoute: typeof PublicTestimonialsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicTestimonialsRoute: PublicTestimonialsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  CoursesRoute: CoursesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
